name = "SatBasedTrees"
uuid = "44de4f9f-f425-403b-a7e6-69d22c13e376"
authors = ["Perro2110 <perrottamarco2011@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PicoSAT = "ff2beb65-d7cd-5ff1-a187-74671133a339"
Satisfiability = "160ab843-0bc6-4ba4-9585-b7478b70f443"
SoleDecisionTreeInterface = "de8eae22-3630-40e0-868c-abfc4c1bb3da"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
